#4 pripomienky
everlutionsk/symfony-docker pull request #5
Opened 2017-08-11 15:36 UTC by ttibensky

2017-08-14 11:13 UTC, ivanbarlog requested changes

2017-08-14 11:13 UTC, ivanbarlog commented on compose
> +if [ ! -f ./ops/env/docker.env ] || [ ! -f ./ops/env/symfony.env ]; then
`docker.env` shouldn't be required - that's why we have if condition on L13

2017-08-14 11:13 UTC, ivanbarlog commented on compose
> +    docker rm -f $(docker ps -a -q) && \
we don't want to involve `docker` -> here we want `docker-compose {...} down`

2017-08-14 11:13 UTC, ivanbarlog commented on compose
> +    docker-compose $COMPOSE_FILE stop && \
what is `&& \` for?

2017-08-14 11:13 UTC, ivanbarlog commented on compose
> +if [ $1 = "up" ]; then
I like this approach

2017-08-14 11:13 UTC, ivanbarlog commented on ops/docker-compose-dev.yml
> +    container_name: mysql
why do we need `container_name`?

2017-08-14 11:13 UTC, ivanbarlog commented on ops/docker-compose-dev.yml
> +  mysql:
Why have you renamed it from `db` to `mysql`?

2017-08-14 11:16 UTC, ttibensky commented on ops/docker-compose-dev.yml
> +    container_name: mysql
if I don't specify it, it will add `ops_` prefix

2017-08-14 11:16 UTC, ttibensky commented on ops/docker-compose-dev.yml
> +  mysql:
because you can have multiple databases in one project. `db` is misleading

2017-08-14 11:17 UTC, ttibensky commented on compose
> +    docker-compose $COMPOSE_FILE stop && \
to be able to write a single bash command on multiple lines. && because I want the rest of command to not execute if one of them fails

2017-08-14 11:17 UTC, ttibensky commented on compose
> +    docker rm -f $(docker ps -a -q) && \
docker-compose down doesn't remove containers. I will try to find a way of doing it with docker compose, haven't checked logs yet

2017-08-14 11:29 UTC, ivanbarlog commented on compose
> +    docker rm -f $(docker ps -a -q) && \
`docker-compose down` removes containers

2017-08-14 11:30 UTC, ivanbarlog commented on compose
> +    docker-compose $COMPOSE_FILE stop && \
ok, np

2017-08-14 11:30 UTC, ivanbarlog commented on ops/docker-compose-dev.yml
> +    container_name: mysql
so?

2017-08-14 11:46 UTC, ttibensky commented on compose
> +    docker rm -f $(docker ps -a -q) && \
didn't work for me when I tried, thats why I used docker rm.. will try again

2017-08-14 11:48 UTC, ttibensky commented on ops/docker-compose-dev.yml
> +    container_name: mysql
its nice to see short container names like `mysql` or `php-cli` instead of `ops_php-cli` and `ops_mysql` when you do `docker ps`

2017-08-14 12:44 UTC, ivanbarlog commented on compose
> +    docker rm -f $(docker ps -a -q) && \
which version of `docker-compose` do you use?

2017-09-03 16:59 UTC, ivanbarlog commented on ops/docker-compose-dev.yml
> +    container_name: mysql
Use `docker-compose` - will resolve all of your problems with container naming...

2017-09-24 17:06 UTC, ivanbarlog commented
@ttibensky 

Please checkout https://github.com/everlutionsk/symfony-docker/releases/tag/v2.0.0 and if you are happy with it we can close this pull request.

I have get some ideas from this PR.

2017-09-26 13:31 UTC, closed without merging